// This file is automatically generated. Do not edit it directly.
// NOTE (segurança): este arquivo foi customizado. Se o Lovable regenerá-lo,
// preserve a lógica do token de sessão (header `x-app-token`) abaixo.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';
import { getSessionToken } from '@/lib/authSession';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;


function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // apikey identifica o projeto (chave publishable — pública por design).
    headers.set('apikey', supabaseKey);

    // Modelo de sessão no servidor: o token opaco (staff/CEO logado) vai no
    // header `x-app-token`. Os helpers do RLS validam esse token no banco.
    // O papel do Postgres continua `anon`; a identidade vem do token. Por
    // isso NÃO enviamos o token como Bearer (o PostgREST rejeitaria).
    const sessionToken = getSessionToken();
    if (sessionToken) {
      headers.set('x-app-token', sessionToken);
    }
    // Chaves publishable novas são opacas, não são JWT — remover o Bearer.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    return fetch(input, { ...init, headers });
  };
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
  },
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});

/**
 * No modelo de sessão no servidor, o token é opaco (não é JWT) e vai no
 * header `x-app-token` das chamadas REST/RPC. O Realtime (websocket) NÃO
 * usa esse header e NÃO deve receber o token como access_token — isso
 * quebraria a validação. Por isso o Realtime opera sempre com a apikey
 * anônima, e as telas do painel que precisam de atualização ao vivo usam
 * polling. Mantido como no-op para compatibilidade das chamadas existentes.
 */
export function applyRealtimeAuth(): void {
  /* no-op — ver comentário acima */
}
